### ISSUE TITLE
Regarding sn75176 IO levels

### ISSUE THREAD

**Issue by muhammadelmogy** [Expatria-Technologies/grblhal_2000_PrintNC#9]
I see that you are using the sn75176 IC for RS485 interface and feeding the IC with 5V!
According to the datasheet, minimum Vcc is  4.75V and you are feeding the comm lines(SDA, SCL) directly to the Teensy!
From what I know the [Teensy4.1 pins is 3.3V tolerance not 5v tolerance ](https://github.com/TeensyUser/doc/wiki/Teensy-Compatibility)unless I am wrong, can you explain this issue?
Shouldn't you be using some kind of voltage translator ?

**Comment by andrewmarles** [comment]
Yes, it is a 5V part.  VCC range is 4.75 to 5.25V so the 5V supply is completely correct.  The minimum input voltage for logic high is 2V so there is no problem feeding the TX from teensy into this part at 3.3V.

In the RX direction, there is a voltage divider (R68, R69) so that the maximum voltage seen at the teensy is ~3.1V, again this is well above the minimum logic high level of the teensy and there is no 5V logic at the teensy pins.

No discrete translator is required.

**Comment by muhammadelmogy** [comment]
I do not know how did I fail to notice this voltage divider, but in that case wouldn't that affect the rise time of the signal, I am wondering what is the max safe baud rate in that case?

**Comment by andrewmarles** [comment]
No issues with 115200 if the vfd supports it.
